<?php

/**
 * @file
 * Contains fut_content.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fut_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fut_content module.
    case 'help.page.fut_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Futurium Content module contains content related configurations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_node().
 */
function fut_content_preprocess_node(array &$variables) {

  // Set custom logic for date.
  $created = $variables['node']->created->value;
  $changed = $variables['node']->changed->value;

  $output = [];
  $output[] = [
    '#theme' => 'markup',
    '#markup' => \Drupal::service('date.formatter')->format($created, 'custom', 'j F Y'),
  ];

  if (!empty($changed) && ($changed <> $created)) {
    $delay = \Drupal::service('date.formatter')->formatInterval(time() - $changed, 1);
    $delay = t('@space- updated @delay ago', [
      '@delay' => $delay,
      '@space' => ' ',
    ]);
    if ($changed > strtotime('-1 hour')) {
      $delay = t('@space updated last hour', [
        '@space' => ' ',
      ]);
    }
    $label = t('updated');
    $delay_item = [
      '#type' => 'html_tag',
      '#tag' => 'span',
      '#attributes' => [
        'class' => "text-muted last-$label",
      ],
      '#value' => $delay,
    ];
    $output[] = $delay_item;
    $variables['date'] = render($output);
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fut_content_form_node_fut_post_form_alter(&$form, $form_state) {
  // Ensure actions and advanced go to bottom of form.
  $form['advanced_expand'] = [
    '#type' => 'details',
    '#title' => t('More options'),
    '#weight' => 9998,
  ];
  $form['advanced_expand']['advanced'] = $form['advanced'];
  unset($form['advanced']);

  $form['actions']['#weight'] = 9999;
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * Alter the IEF widget button labels.
 */
function fut_content_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if (isset($element['#ief_id'])) {
    if (isset($element['actions'])) {
      foreach ($element['actions'] as $k => &$button) {
        if (strpos($k, 'ief_') === 0) {
          $old_string = str_replace(' media', '', $button['#value']->__toString());
          if ($element['#title'] == 'Post Image') {
            $element['#title'] = t("Image");
          }

          $old_string = ($old_string == 'Add existing')
            ? 'Use existing'
            : $old_string;

          $button['#value'] = t("@action @type_singular", ['@action' => $old_string, '@type_singular' => $element['#title']]);
        }
      }
    }
  }
}

/**
 * Implements hook_field_widget_multivalue_form_alter().
 */
function fut_content_field_widget_multivalue_form_alter(&$elements, $form_state, $context) {
  if ($context['widget']->getPluginId() == 'entity_reference_paragraphs') {
    foreach ($elements['add_more'] as &$button) {
      if (isset($button['#value'])) {
        $button['#value'] = t("@type", $button['#value']->getArguments());
      }
    }
  }
}

/**
 * Implements hook_paragraphs_widget_actions_alter().
 */
function fut_content_paragraphs_widget_actions_alter(array &$widget_actions, array &$context) {
  foreach ($widget_actions['actions'] as $widget_action_key => $widget_action) {
    array_unshift($widget_actions['dropdown_actions'], $widget_action);
    unset($widget_actions['actions'][$widget_action_key]);
  }
}
