ahoyapi: v2
commands:
  up:
    cmd: "docker-compose -f docker/docker-compose.yml up -d "
    usage: Start the docker-compose containers.

  down:
    cmd: "docker-compose -f docker/docker-compose.yml down "
    usage: Stop the docker-compose containers.

  phpsh:
    cmd: "docker exec -u 1000 -it php bash"

  codesniff:
    cmd: "docker exec -u 1000 -it php ./bin/robo qa -z cs"
    usage: Run behat tests.

  behat:
    cmd: "docker exec -u 1000 -it php ./bin/robo qa -z behat"
    usage: Run behat tests.

