stages:
  - build

build:
  stage: build
  script: 
    - composer install
    - cd ..
    - echo ${CI_PROJECT_NAME}
    - echo ${CI_COMMIT_TAG}
    - tar -zcf ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tgz ${CI_PROJECT_NAME} --exclude-vcs --exclude="scripts"
    - cp ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tgz ${CI_PROJECT_NAME}
  only:
    - ci