stages:
  - build

build:
  stage: build
  script: 
    - composer install
    - cd ..
    - tar -zxvf --exclude-vcs --exclude="" ${CI_PROJECT_NAME}-{CI_COMMIT_TAG}.tar.gz
    - cp ${CI_PROJECT_NAME}-{CI_COMMIT_TAG}.tgz ${CI_PROJECT_NAME}
  only:
    - ci