stages:
  - release
  - build

build:
  stage: build
  script: 
    - composer install
    - cd ..
    - echo ${CI_PROJECT_NAME}
    - echo ${CI_COMMIT_TAG}
    - tar -zcf ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tgz ${CI_PROJECT_NAME} --exclude-vcs --exclude="scripts"
    - cp ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tgz ${CI_PROJECT_NAME}
  only:
    - tags
  artifacts:
    paths:
    - ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tgz
    expire_in: 1 day

release:
  stage: release
  image: python:3
  script:
    - pip3 install gitlab-release
    - gitlab-release --link-artifact *.tgz
  artifacts:
    paths:
      - ./*.tgz
  only:
    - tags
