# .gitlab-ci.yml
# Shell runner on AWS EC2 Instance.
stages:
  - test
  - package
  - release
#  - packer
#  - deploy

PHPCS:
  stage: test
  script:
    - docker run --user 1000:1000 --name php_cs --rm -i -v $(pwd):/var/www/html horaciolopesqq/phpnode composer install || exit 1
    - docker run --user 1000:1000 --name php_cs --rm -i -v $(pwd):/var/www/html horaciolopesqq/phpnode ./bin/robo qa -z cs || exit 1
  allow_failure: true
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "refactor"
  tags:
    - shell

Behat:
  stage: test
  script:
    - cp config.yml.dist config.yml
    - bash install --force
    - docker exec -u 1000 php ./bin/robo bt
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "refactor"
  after_script:
    - chmod -R 0777 .
  tags:
    - shell

Create artifact:
  stage: package
  script:
    - cp config.yml.dist config.yml
    - bash install --force
    - docker exec -u 1000 php ./bin/robo ti
    - docker exec -u 1000 php ./bin/robo rp ${CI_PROJECT_NAME}-${CI_BUILD_TAG}
  after_script:
    - chmod -R 0777 .
  artifacts:
    paths:
    - ${CI_PROJECT_NAME}-${CI_BUILD_TAG}.zip
  only:
    - tags
  tags:
    - shell

Create release:
  stage: release
  image: python:3
  script:
    - pip3 install gitlab-release
    - gitlab-release --link-artifact *.zip
  artifacts:
    paths:
      - ./*.zip
  only:
    - tags
  tags:
    - docker

#Packer:
#  stage: packer
#  script:
#    - >
#      packer build
#      -var "platform_version=${PLATFORM_PACKAGE_VERSION}"
#      -var "gitlab_private_token=${PRIVATE_TOKEN}"
#      -var "tag=${CI_BUILD_TAG}"
#      packer.json
#  only:
#    - tags
#  tags:
#    - shell

#Aws:
#  stage: deploy
#  script:
#    - ./scripts/aws/rotate_lcfg.sh ${PRODUCTION_STACK_NAME} ${CI_PROJECT_NAME}
#  only:
#    - tags
#  tags:
#    - shell
