# Project information.
project:
  name: FuturiumD8
  url: http://web
  root: /var/www/html/web/
  environment: development

# Site information.
site:
  name: Futurium
  mail: email@example.com
  profile: minimal
  update: false
  locale: en
  hash_salt: nBLOu5CNVuJ9Zm0dDE4KTCToRbtmbz0mb9WFx6bcTDsoKRPlvNsA5t4QQ6JxhgzH7nrpFHrrKw

# Administrator account.
account:
  name: admin
  password: admin
  mail: admin@example.org

# Database parameters.
database:
  name: futuriumd8
  user: mysql
  password: mysql
  host: localhost
  port: 3306
  root_password: password
  prefix: ''

# Binaries
bin:
  drush: ./vendor/bin/drush

# Behat
behat:
  api_driver: drupal
  webdriver_host: http://172.17.0.1:4444/wd/hub

# Here you can specify environment overrides.
#environment:
#  settings:
#    trusted_host_patterns:
#      - "dev.europa.eu$"
#    http_client_config:
#      proxy:
#        http: "http://username:password@host:port"
#        https: "http://username:password@host:port"

