#!/usr/bin/env bash
FORCE=${1:-no}
REBUILD_CONTAINERS=${2:-no}

if [ ! -x "$(command -v yq)" ]; then
  echo "You need to install yq."
fi

if [ "$FORCE" != "no" ]; then
  FORCE="--force"
else
  FORCE=""
fi

if [ ! -f "config.yml" ]; then
  cp config.yml.dist config.yml
  echo "Check your settings on config.yml and re-run this script."
  exit 1
fi

# Prepare the environment.
> .env
echo PROJECT_NAME=$(yq r config.yml "project.name") >> .env
echo ENVIRONMENT=$(yq r config.yml "project.environment") >> .env

# Check if we're on beanstalk.
# If we aren't, add the database info to .env
# If we are, the database info should already be in place.
if [ -z $EFS_MOUNT_DIR ]; then
  echo DATABASE_NAME=$(yq r config.yml "database.name") >> .env
  echo DATABASE_USERNAME=$(yq r config.yml "database.user") >> .env
  echo DATABASE_PASSWORD=$(yq r config.yml "database.password") >> .env
  echo DATABASE_ROOT_PASSWORD=$(yq r config.yml "database.root_password") >> .env
  echo DATABASE_PREFIX=$(yq r config.yml "database.prefix") >> .env
  echo DATABASE_HOST=$(yq r config.yml "database.host") >> .env
  echo HASH_SALT=$(yq r config.yml "site.hash_salt") >> .env
fi
echo DATABASE_DRIVER=mysql >> .env
echo DATABASE_PORT=$(yq r config.yml "database.port") >> .env
echo DATABASE_ROOT_PASSWORD=$(yq r config.yml "database.root_password") >> .env

echo BEHAT_API_DRIVER=$(yq r config.yml "behat.api_driver") >> .env
echo BEHAT_WD_HOST_URL=$(yq r config.yml "behat.webdriver_host") >> .env
echo USER_ID=1000 >> .env
echo GROUP_ID=1000 >> .env
echo SITE_PROFILE=$(yq r config.yml "site.profile") >> .env

# Export the vars in .env.
# The .env file should be present in the folder from where this script is invoked.
if [ ! -f ".env" ]; then
  echo "No .env file present. Stopping."
  exit 1
fi

export $(egrep -v '^#' .env | xargs)

# Check if docker and docker-compose are installed.
if [ -x "$(command -v docker)" ] && [ -x "$(command -v docker-compose)" ]; then
  # Docker is installed, carry on with docker.
  echo "Using docker-compose."

  if [ "$REBUILD_CONTAINERS" = "yes" ]; then
      # Kill all running containers.
      RUNNING_CONTAINERS=$(docker ps -q)
      if [ ! -z "$RUNNING_CONTAINERS" ]
      then
        echo "Killing running containers."
        KILL=$(docker kill $RUNNING_CONTAINERS)
      fi
  fi

  docker-compose -f docker/docker-compose.yml up -d \
  && docker exec -u 1000 -it php bash -c 'if [[ $ENVIRONMENT == "development" ]]; then composer install; else composer install --no-dev; fi' \
  && docker exec -u ${USER_ID} php echo "" \
  && docker exec -u ${USER_ID} php ./vendor/bin/robo pic $FORCE
else
  # No docker, install on bare metal.
  echo "Bare metal install."
  if [ "$ENVIRONMENT" = "development" ]; then
    composer install;
  else
    composer install --no-dev;
  fi
  ./vendor/bin/robo pic $FORCE
fi
