#!/usr/bin/env bash
# Export the vars in .env.
# The .env file should be present in the folder from where this script is invoked.
REBUILD_CONTAINERS=${1:-no}

if [ ! -f ".env" ]; then
  echo "No .env file present. Stopping."
  exit 1
else
  echo ".env file found."
fi

# Check if docker is installed.
if [ -x "$(command -v docker)" ]; then
  export $(egrep -v '^#' .env | xargs)

  if [ "$REBUILD_CONTAINERS" = "yes" ]; then
      # Kill all running containers.
      RUNNING_CONTAINERS=$(docker ps -q)
      if [ ! -z "$RUNNING_CONTAINERS" ]
      then
        echo "Killing running containers."
        KILL=$(docker kill $RUNNING_CONTAINERS)
      fi
  fi

  docker-compose -f docker/docker-compose.yml up -d \
  && docker exec -u 1000 -it php bash -c 'if [[ $ENVIRONMENT == "development" ]]; then composer install; else composer install --no-dev; fi' \
  && docker exec -u ${USER_ID} php echo "" \
  && docker exec -u ${USER_ID} php ./bin/robo pic --force
else
  # No docker, install on bare metal.
  if [[ $ENVIRONMENT == "development" ]]; then
    composer install;
  else
    composer install --no-dev;
  fi
  ./bin/robo pic
fi

