version: "3"

services:

  # Nginx
  web:
    image: nginx:latest
    container_name: "nginx"
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      # Add our site nginx config.
      - ./config/nginx/nginx.site.conf:/etc/nginx/conf.d/default.conf
      - ..:/var/www/html/
    ports:
      - "80:80"
    links:
      - php

  # PHP
  php:
    container_name: "php"
    image: horaciolopesqq/php:latest
    volumes:
      # Add a configurable php.ini
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php_overrides.ini
      - ..:/var/www/html
      - ${HOME}/.composer:/.composer
      - /tmp:/tmp
    links:
      - mysql

  # Solr
  solr:
    container_name: "solr"
    image: solr:5.5.5
    ports:
      - "8983:8983"
    volumes:
      - ./config/solr:/opt/solr/solr_conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - ./solr_conf/drupal

  # MySQL
  mysql:
    container_name: "mysql"
    image: mysql:5.7.22
    restart: "no"
    command: --max_allowed_packet=1073741824
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      - "3306:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    environment:
        PMA_HOST: $DATABASE_HOST
        PMA_USER: $DATABASE_USER
        PMA_PASSWORD: $DATABASE_PASSWORD
        PHP_UPLOAD_MAX_FILESIZE: 1G
        PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8080:80"
    links:
      - mysql

  # MailHog
  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"

  # Portainer
  portainer:
    image: portainer/portainer
    container_name: "portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9000"

  # Selenium
  selenium:
    image: selenium/hub:3.141.59-copernicium
    container_name: "selenium_hub"
    ports:
      - "4444:4444"

  # Chrome driver
  chrome:
    image: selenium/node-chrome-debug:3.141.59-copernicium
    container_name: "chrome"
    ports:
      - "5900:5900"
    depends_on:
      - selenium
    environment:
      - HUB_HOST=172.17.0.1
      - HUB_PORT=4444

  # Node
  #node:
  #  container_name: "node"
  #  build:
  #    context: ./build/node
  #    dockerfile: Dockerfile
  #    args:
  #      USER_ID: ${USER_ID}
  #      GROUP_ID: ${GROUP_ID}
  #  working_dir: "${PROJECT_THEME_PATH}"
  #  expose:
  #    - "3000"
  #  volumes:
  #    - ..:/var/www/html
  #  command: bash -c "npm install && tail -f /dev/null"

volumes:
  data:
