<?php

/**
 * @file
 * Contains fut_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fut_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fut_paragraphs module.
    case 'help.page.fut_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Futurium Paragraphs module contains paragraph related configurations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fut_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'fut_paragraph_summary' => [
      'variables' => [
        'summary' => NULL,
        'class' => NULL,
      ],
    ],
  ];
}
