<?php

/**
 * @file
 * Contains fut_media.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fut_media_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fut_media module.
    case 'help.page.fut_media':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Futurium Media module contains media related configurations.') . '</p>';
      return $output;

    default:
  }
}
