<?php

/**
 * @file
 * Contains webtools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webtools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webtools module.
    case 'help.page.webtools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module provides all webtools related features') . '</p>';
      return $output;

    default:
  }
}
