<?php

/**
 * @file
 * Contains aws_info.module.
 */

/**
 * Implements hook_help().
 */
function aws_info_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aws_info module.
    case 'help.page.aws_info':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('AWS Info') . '</p>';
      return $output;

    default:
  }
}

/**
 * Add environment class to body tag.
 */
function aws_info_preprocess_html(&$variables) {
  if (getenv('ENVIRONMENT')) {
    $environment = strtolower(getenv('ENVIRONMENT'));
    $variables['attributes']['class'][] = $environment;
  }
}
