<?php

/**
 * @file
 * Contains fut_group.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fut_group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fut_group module.
    case 'help.page.fut_group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Futurium Group module contains group related configurations.') . '</p>';
      return $output;

    default:
  }
}
